version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck      # This now includes gosimple and unused
    - misspell
    - gocritic
    - errname
    - gosec
  exclusions:
    rules:
      - linters:
          - errcheck
        text:  "Error return value of `.*\\.Close` is not checked"
      - linters:
          - errcheck
        text: "Error return value of `rows\\.Close` is not checked"
      - linters:
          - errcheck
        text: "Error return value of `.*Body\\.Close` is not checked"
      - linters:
          - gosec
        text: "G304.*file inclusion via variable"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/go-message-dispatcher

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0